---
title: Code For Boston
timezone: UTC
markdown: kramdown
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  rooms:
    title: Rooms
    output: true
email: hello@codeforboston.org
description:
  'Part of the Code for America Brigade network, we are a volunteer group
  of developers, designers, data geeks, and citizen activists who use creative technology
  to solve civic and social problems.'
baseurl: ''
url: https://www.codeforboston.org
# NOTE:If you change the below donate_url you should also update the URL here: https://github.com/codeforboston/.github/FUNDING.yml
donate_url: https://codeforamerica.org/donate-to-a-brigade?utm_campaign=Code%20for%20Boston&utm_source=codeforboston.org
hackpad_url: https://codeforboston.hackpad.com/
twitter_url: https://twitter.com/codeforboston
github_url: https://github.com/codeforboston
meetup_url: https://meetup.com/Code-For-Boston
blog_url: https://medium.com/@CodeForBoston
events_url: https://cal.codeforboston.org
zoom_url: https://codeforamerica.zoom.us/meeting/register/tJwpdO2hpj8qE9VQwzZGNMduNOXb-GNLcNY0
slack_url: https://communityinviter.com/apps/cfb-public/code-for-boston-slack-invite
youtube_url: https://www.youtube.com/c/codeforboston
facebook_url: https://www.facebook.com/codeforboston/
instagram_url: https://www.instagram.com/codeforboston/
newsletter_url: https://eepurl.com/5UcLX
slack_team_id: T0556DP9Y
plugins:
  - jekyll-redirect-from
